name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.json'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_REPO: ${{ secrets.KEY_REPO }}
      KEY_TOKEN: ${{ secrets.KEY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Android Keystore
        if: ${{ env.KEY_REPO != '' && env.KEY_TOKEN != '' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ env.KEY_REPO }}
          token: ${{ env.KEY_TOKEN }}
          path: keystore
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleAppRelease --build-cache --parallel --daemon --warning-mode all
          ./gradlew -Pfrpc :app:assembleFrpcRelease --build-cache --parallel --daemon --warning-mode all
      - name: Organize the Files
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          cp -rf ${{ github.workspace }}/app/build/outputs/apk/*/*/*.apk ${{ github.workspace }}/apk/
      - name: Upload Lanzou
        run: |
          echo "上传APP至蓝奏云"
          versionName=$(sed -n 's/versionName = "\(.*\)"/\1/p' ${{ github.workspace }}/app/build.gradle.kts)
          gitHead=$(git rev-parse --short HEAD)
          tag_name=$versionName-$gitHead
          echo "versionName=$versionName"
          python3 $GITHUB_WORKSPACE/keystore/scripts/lzy.py "${{ github.workspace }}/apk/" "8227905" "$tag_name"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FQWeb
          path: ${{ github.workspace }}/下载地址.txt